export const probeSettings = {
  siteName: "CCResDoc compatibility probe",
  siteDescription: "zfb 2.20.2 + zudo-doc 5.27.0 node-free architecture probe",
  port: 4892,
  base: "/",
  trailingSlash: true,
  docsDir: "src/content/docs",
  defaultLocale: "en",
  locales: {},
  versions: false,
  onBrokenMarkdownLinks: "warn",
  sidebarResizer: true,
  sidebarToggle: true,
  dynamicPageTransition: true,
  imageEnlarge: false,
  findInPage: true,
  claudeResources: false,
  codexResources: false,
  siteTreeNavIgnore: [],
  docHistory: false,
  llmsTxt: false,
  changelogs: false,
  themePack: "default",
  themePacks: undefined,
};
